config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_page#home'
  get 'static_page/home'
  get 'categories/new'
  get 'categories/:id', to: 'categories#show'
  
  # Users Routes
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/questions', to: 'questions#new'
  post '/questions', to: 'questions#create'
 
  get '/categories', to: 'categories#new'
  post '/categories', to: 'categories#create'

  resources :answers 
  resources :questions do
    member do
     put 'like', to: 'questions#like'
     put 'unlike', to: 'questions#unlike'
    end
  end
  resources :categories do
    post 'search', :on => :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  acts_as_votable
  has_many :answers
  belongs_to :user
  belongs_to :category, optional: true
  validates :description, length: { maximum: 400 }, presence: true
  
  def self.search(search)
    if search
      category = Category.find_by(name: search)
      if category
        self.where(category_id: category)
      else
        Question.includes(:answers).all
      end
    else
      Question.includes(:answers).all
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :like, :unlike]

  # GET /questions
  # GET /questions.json
  def index
    #TODO-sql: .includes(...)
    @questions = Question.includes(:answers).search(params[:search])
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answers = Answer.where(question_id: params[:id]).paginate(page: params[:page], per_page: 25)
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    @question.category_id = question_params[:category_id]

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, notice: 'Question cannot be created' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @question.liked_by current_user
    redirect_to @question
  end
  
  def unlike
    @question.unliked_by current_user
    redirect_to @question
  end 
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :description, :category_id, :user_id, :search)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def answer_cache_key_of(answer)
    "answer-#{answer.id}-#{answer.updated_at}"
  end
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <!--Question description-->

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>


  <!--Category dropdown selection-->

  <div class="field">
    <%= form.label :category %>
    <%= form.collection_select :category_id, Category.all, :id, :name, prompt: "Please select a category" %>
  </div>


  <!--Add Category button-->

  <div id="nqct">
    <a id="adqlnk" href="/categories/new">
      <span id="adqic">
        <%= image_tag("icons/icon-idea.png", :alt => "Add Category Icon") %>
      </span>
      <span id="adqlb">Add Category!</span>
    </a>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', :back %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.description %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "question_forms" %>
<% end %>

<section id="mainfrm">
    <div class="container">
        <div class="frmhddr">
            <h1>Ask a New Question</h1>
        </div>
        <div class="adqcwrp">
            <div class="adqc">
                <%= form_for(:question, url: questions_path) do |q| %>
                    <div class="fldwrp">
                        <%= q.label :title %>
                        <%= q.text_field :title %> 
                    </div>               
                    <div class="fldwrp">
                        <%= q.label :description %>
                        <textarea name="question[description]" id="question_description" maxlength="400" rows="8"></textarea>
                    </div>
                    <div class="fldwrp fldcateg">
                        <%= q.label :category_id %>
                        <%= q.collection_select :category_id, Category.all, :id, :name, prompt: "Please select a category" %>
                     </div>
                    <span>Click <a href="/categories/new" target="_blank">here</a> to add a category</span>
                    <div class="btnwrp categbtn">
                        <%= q.submit "Create", class: "btn btn-primary" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>


<%= link_to "Back", questions_path %>

app/views/questions/show.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "questions" %>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @question.description %>
  <strong>Likes:</strong>
  <%= @question.get_likes.size %>
</p>

<% if current_user != nil && @question.user_id == current_user.id %>
  <%= link_to 'Edit', edit_question_path(@question) %> |
<% end %>
<%= link_to 'Back', root_path %> |
<%= link_to 'Add Answer', new_answer_path({:qn_id => @question.id}) %> | 
<%= link_to 'Like', like_question_path(@question), method: "put" %> |
<%= link_to 'Unlike', unlike_question_path(@question), method: "put" %>

<% @answers.each do |answer| %>
  <div class="ansctnr">
    <div>User: <%= answer.user_id %></div>
    <div>Answer: <%= answer.description %></div>
    <% if current_user != nil && current_user.id == answer.user_id %>
      <%= link_to "Edit", edit_answer_path(answer) %>
      <%= link_to "Delete", "/answers/#{answer.id}", method: "delete" %>
    <% end %>
  </div>
<% end %>

<%= will_paginate @answers %>